services:
  webapp:
    image: ghcr.io/it4change/reformer.network/webapp
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
      target: branded
      args:
        OCELOT_VERSION: ${OCELOT_VERSION:-master}
    environment:
      GRAPHQL_URI: http://backend:4000
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: ghcr.io/it4change/reformer.network/backend
    build:
      context: .
      dockerfile: ./docker/webapp.Dockerfile
      target: branded
      args:
        OCELOT_VERSION: ${OCELOT_VERSION:-master}
    environment:
      CLIENT_URI: http://localhost:3000
      GRAPHQL_URI: http://backend:4000
      NEO4J_URI: bolt://neo4j:7687
    ports:
      - 4000:4000
    depends_on:
      - neo4j

  maintenance:
    image: ghcr.io/it4change/reformer.network/maintenance
    build:
      context: .
      dockerfile: ./docker/maintenance.Dockerfile
      target: branded
      args:
        OCELOT_VERSION: ${OCELOT_VERSION:-master}
    ports:
      - 3001:80

  neo4j:
    image: ghcr.io/ocelot-social-community/ocelot-social/neo4j
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_allow__format__migration: "true"
      NEO4J_dbms_allow__upgrade: "true"
      NEO4J_dbms_security_procedures_unrestricted: algo.*,apoc.*

