secrets:
    database:
        env: null
    badgelookup:
        env:
            SECRET_REQUEST: ENC[AES256_GCM,data:yxonZ+F+RmlUVBHC3V63fVTN854=,iv:B3r/I29xTOqU/b59drwYN5RxLsBAa8j0sLgH+6Kdu/I=,tag:DhNGldACyBO+7lXJkeR9Cg==,type:str]
            SECRET_SUBMIT: ENC[AES256_GCM,data:1CM6ST87La62ynY1Eql9SEX5owk=,iv:cZWBBEz10/vr6MdQ7nIlxaE+CaxWTSJmTCf6JoWP7+k=,tag:MeYK//+aBnIZM4wlKU6vPg==,type:str]
sops:
    age:
        - recipient: age1al36hkk8can83zpxq8qyy07gpv83hdw9vchfly5f264kanz405as283a00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNUlFSVQzL3ZIdmdKTGdr
            ZzRwR1Y1Uzk1SzlSc3dtTUU2dVl1VVRvTFI0CmJpZGhOSnRsU0pFVnMxbkZhR09W
            eVo1Z0lEZzJteVZ4TVFPRUc1UDhmWDQKLS0tIG1lb3BkY1ozUzlOYnViYUJzVlQ4
            REhvcG5xOWozdlhXVDZvUlN6eXZzZmsKPHY19y/GIfn9CK9JjcG6cjUMNez3iJzm
            md5oCGzT7fnPHwagY1GBiGVUColcrtKsiXXSktQ6HUC5oOV34mKARA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR2V0bGVmVXRzeXlrd2dk
            cTRKbG9tUEw3MkVkMWM5RHE1RHprTWowZURzCm9LOVo4ekFsQmZxM0ZZaW5PRG55
            a2g4OUJzajZkM3FFUFppRGJmSVlqcUEKLS0tIDZMUHB6RDY4RVlSbGF1cElaVFBO
            ZXZGNXFwUlQ5TUQ2Vm5ZS3NXTTJuV3MK7rVuVTvmZER7eViP/EjdmN9I4+CeUj+g
            4YqBC4MP/RoQXlISe0KJR5Dgpr32VSopV43H9LcrIAIg5tmGSUUi3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bnJNMlRIS1lHbVZrblo1
            cDBXOGlwc2lhelJES1E0a3Fuc2xzS3VqaVRnCnFNblhaeHVBY0VHUFdENERhZjF2
            Y1VyZkx6SDg2REhCQ01WeVE5MGo2Y1UKLS0tIGJJR1hNLzExZzhpOVI2Y0pTd0lI
            eCtTODRZeWNlSG5WVTVISGZ2TmdFVkkKk5YcSG+yAvqfW3wZ0G6PR/zLkwzJ3WOc
            0FwI+/eS/p58J2q/sB+01tJ2Xse8RJrEFmCEVt3hr9IBxQcmKeIBiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15arcg8x6ltnsacwalvny0h2d4d4wkdmax328mw3v5vda9zm97uqshtavmr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dXFzY2tTYy9zMFNndlRu
            TFk4ejczcDIxNHVYQjBCWC9LREozdFlBR1VBCitDN25vUHk4eWNZVWYrQ3daMXBn
            ZXZSLzN2YldVbklURHR1YnY3Y0Z5UTQKLS0tIFJjY3FkZDUxc1NFWng3VWdMbDZv
            VU9sRllPZndNYlFQcEtqcXAxcGZraWsKFZelC/njfCPhd+SFB89kCkVhRq/SsSlc
            xMStM7bVLS3R7WArtJOFLuvJblUkDekv2fl2JEEPAgu5+ZbdZqc2vQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1khw2eps099audp3uu5s9rk07qznllh5c8a43gv5dtpnq2a7lue6qrehn5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNVBEZHFqZ05pelVmb1hv
            TjIzR3M4enloVGtmUXhwakpwNlNYazFZTmdjCkgwYWRMaWdZYmtQbUZza0NPd0JR
            bXZlazhlaWFTaTdZcUlYamNPNWtuMWsKLS0tIEU4eVdXRUNCUjNRRlpWQjZJeitv
            UE5oeC9uZng0K0ZyZDNScVl3dStxRFEKS7Y3mcdBdqEKnRD9hK6NllMTqgKwxrmF
            /3cr3BlBHRkMMU6W37mv8GutomfuNvqrrCrNWmf6wd8Z3GkYoCWitA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6mzqe0cejajzt0c7nwdjz4xvs4hjct9d8hrgj60e7unzyfd7prsn0npe5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTWlwcVJpYVNsQkRkL0lK
            SGp3ZjhiMStlV1MxdWp5UnBnQW9qU1lZS0FJClhRYUQwU1U5cUVTazdnTXJvOUZT
            UE5lNkJMa0pyL2xjZVlFeTZhQU9GZVEKLS0tIGFsZHQ4TlVsLzhUT08wK2hxaFM3
            THVUVGd5TVg5Zm45aVB0OXhFT0dCaXcKFPCzaA2Tmv4BqLXQdjn5ZPVdtKQfRNNE
            hTnWQBdhYv+xkB+HKA1m4CLM4fA4GkpwnuD8B96QlfFg0Beu2PgQXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t0ufylv5xfwhmcamu4gpwtay4wcuyqgzlkht4t04s9qjl8xjks9skxrt02
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOGRxaU80dmRzaGZ4dFZh
            SUV6ZVhHU1N2aFVLS0Z5YTdvYWIzUmtMWTAwCjFlVjUxYWhod3FvVVkvRUZpbmt4
            RkdxR1FNRVFUSXF5bWtpaldHSmIxWlEKLS0tIGR2a2FpakZsRjlpWWoyU3FXOEhT
            TUt0SEJvekV6QjFVd2JVRDkyQkFIbTQKDEXppOJRkDPNTFIdqO5ItfiDgTT0C95T
            hb8nfDzOHq82L8yscG/VWYEFhKQNPhdAPIxIJgKWF8XlKk8EfxEqxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-28T07:49:59Z"
    mac: ENC[AES256_GCM,data:TQaIvyaMxf9H10DwpNc9JYe1PJdpf/y8OK0KX02cz4NPD1xqPdzimcYT9Rf+mGFmFsKMpdCHUMjenskMqC8ZUYVnzCTkD4gdgPuf38qK2JKRccRGdrHs49sAB6GuGEePF48RNcc5rQXobSDAQJrCT0Zv933QwImBs2rDP453wfY=,iv:Ok7a8EpjM1zkU9Y6vnPhH2mNgQtRFGVihMWunxKwhT8=,tag:uNClFKUOozkP54NeFk83PA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
