kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-database
spec:
  ports:
  - name: {{ .Release.Name }}-sql
    port: 3306
    targetPort: 3306
  selector:
    app: {{ .Release.Name }}-database
